### ISSUE TITLE
Exclude flagged submissions from Analytics

### ISSUE THREAD

**Issue by BasicallyOk** [mustafa-tariqk/mindscape#41]
**Is your feature request related to a problem? Please describe.**
There is currently nothing stopping flagged submissions from getting into analytics. It should obviously not be the case.

**Describe the solution you'd like**
Every time messages are fetched, it should also cross check if the associated chat was flagged.

**Additional context**
Currently a thing in word cloud, I'm being thoughtful with sentiment analysis

**Comment by mustafa-tariqk** [comment]
Course is over bruv
